#!/bin/sh

echo "-x-x-x-x-x- $(git symbolic-ref --short HEAD) -x-x-x-x-x-"

echo "====== Running build pre-commit ======"

./gradlew spotlessApply

./gradlew clean build

status=$?

git stash pop -q

echo "====== Done with build pre-commit ======"

exit $status