spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DATABASE}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
