spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saudeconnectDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: root
  expiration: 24
